set_property IOSTANDARD LVCMOS18 [get_ports {io_led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property PACKAGE_PIN F22 [get_ports reset]
set_property PACKAGE_PIN Y9 [get_ports clock]


create_clock -period 10.000 -name clock -waveform {0.000 5.000} [get_ports clock]

set_property PACKAGE_PIN T22 [get_ports {io_led[7]}]
set_property PACKAGE_PIN T21 [get_ports {io_led[6]}]
set_property PACKAGE_PIN U22 [get_ports {io_led[5]}]
set_property PACKAGE_PIN U21 [get_ports {io_led[4]}]
set_property PACKAGE_PIN V22 [get_ports {io_led[3]}]
set_property PACKAGE_PIN W22 [get_ports {io_led[2]}]
set_property PACKAGE_PIN U19 [get_ports {io_led[1]}]
set_property PACKAGE_PIN U14 [get_ports {io_led[0]}]
